const SAMPLE_PRODUCTS = [
  {
    name: "Fresh Milk",
    category: "grocery",
    price: 32,
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400",
    stock: 60,
    available: true,
    minStockAlert: 10,
    unit: "500 ml",
    description: "Fresh daily milk for tea, coffee, and breakfast.",
  },
  {
    name: "Bread",
    category: "grocery",
    price: 35,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
    stock: 45,
    available: true,
    minStockAlert: 8,
    unit: "1 pack",
    description: "Soft bread for quick breakfast and evening snacks.",
  },
  {
    name: "Eggs",
    category: "grocery",
    price: 48,
    image: "https://images.unsplash.com/photo-1518569656558-1f25e69d1c89?w=400",
    stock: 80,
    available: true,
    minStockAlert: 12,
    unit: "6 pcs",
    description: "Farm-fresh eggs for your home kitchen.",
  },
  {
    name: "Tea",
    category: "grocery",
    price: 90,
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400",
    stock: 40,
    available: true,
    minStockAlert: 8,
    unit: "250 g",
    description: "Strong village-style tea leaves for everyday brewing.",
  },
  {
    name: "Rice",
    category: "grocery",
    price: 124,
    image: "https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400",
    stock: 70,
    available: true,
    minStockAlert: 10,
    unit: "1 kg",
    description: "Everyday staple rice for home cooking.",
  },
  {
    name: "Cooking Oil",
    category: "grocery",
    price: 168,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400",
    stock: 55,
    available: true,
    minStockAlert: 10,
    unit: "1 L",
    description: "Kitchen essential cooking oil for regular meals.",
  },
  {
    name: "Samosa",
    category: "food",
    price: 20,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400",
    stock: 120,
    available: true,
    minStockAlert: 15,
    unit: "1 pc",
    description: "Crispy hot samosa served fresh from the local kitchen.",
  },
  {
    name: "Veg Burger",
    category: "food",
    price: 65,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
    stock: 75,
    available: true,
    minStockAlert: 12,
    unit: "1 pc",
    description: "Fresh veg burger for a quick and filling snack.",
  },
  {
    name: "Cold Drink",
    category: "food",
    price: 30,
    image: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400",
    stock: 95,
    available: true,
    minStockAlert: 15,
    unit: "250 ml",
    description: "Chilled cold drink for heat and hunger relief.",
  },
  {
    name: "Sweet Tea",
    category: "food",
    price: 15,
    image: "https://images.unsplash.com/photo-1542990253-0f4f5f6f6f9f?w=400",
    stock: 140,
    available: true,
    minStockAlert: 20,
    unit: "1 cup",
    description: "Sweet tea prepared fresh for the village chai break.",
  },
];

const normalizeSeedProduct = (product) => ({
  ...product,
  description: product.description || "",
  minStockAlert: Number.isFinite(Number(product.minStockAlert)) ? Number(product.minStockAlert) : 5,
  stock: Number.isFinite(Number(product.stock)) ? Number(product.stock) : 0,
  price: Number.isFinite(Number(product.price)) ? Number(product.price) : 0,
  available: product.available !== false,
});

module.exports = {
  SAMPLE_PRODUCTS,
  normalizeSeedProduct,
};
